/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeadiRouteImport } from './routes/leadi'
import { Route as KomunikacijasRouteImport } from './routes/komunikacijas'
import { Route as IenakosasZinasRouteImport } from './routes/ienakosas-zinas'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as DarbaRindaRouteImport } from './routes/darba-rinda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadLeadIdRouteImport } from './routes/lead.$leadId'

const LeadiRoute = LeadiRouteImport.update({
  id: '/leadi',
  path: '/leadi',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunikacijasRoute = KomunikacijasRouteImport.update({
  id: '/komunikacijas',
  path: '/komunikacijas',
  getParentRoute: () => rootRouteImport,
} as any)
const IenakosasZinasRoute = IenakosasZinasRouteImport.update({
  id: '/ienakosas-zinas',
  path: '/ienakosas-zinas',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const DarbaRindaRoute = DarbaRindaRouteImport.update({
  id: '/darba-rinda',
  path: '/darba-rinda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadLeadIdRoute = LeadLeadIdRouteImport.update({
  id: '/lead/$leadId',
  path: '/lead/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/darba-rinda': typeof DarbaRindaRoute
  '/funnel': typeof FunnelRoute
  '/ienakosas-zinas': typeof IenakosasZinasRoute
  '/komunikacijas': typeof KomunikacijasRoute
  '/leadi': typeof LeadiRoute
  '/lead/$leadId': typeof LeadLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/darba-rinda': typeof DarbaRindaRoute
  '/funnel': typeof FunnelRoute
  '/ienakosas-zinas': typeof IenakosasZinasRoute
  '/komunikacijas': typeof KomunikacijasRoute
  '/leadi': typeof LeadiRoute
  '/lead/$leadId': typeof LeadLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/darba-rinda': typeof DarbaRindaRoute
  '/funnel': typeof FunnelRoute
  '/ienakosas-zinas': typeof IenakosasZinasRoute
  '/komunikacijas': typeof KomunikacijasRoute
  '/leadi': typeof LeadiRoute
  '/lead/$leadId': typeof LeadLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/darba-rinda'
    | '/funnel'
    | '/ienakosas-zinas'
    | '/komunikacijas'
    | '/leadi'
    | '/lead/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/darba-rinda'
    | '/funnel'
    | '/ienakosas-zinas'
    | '/komunikacijas'
    | '/leadi'
    | '/lead/$leadId'
  id:
    | '__root__'
    | '/'
    | '/darba-rinda'
    | '/funnel'
    | '/ienakosas-zinas'
    | '/komunikacijas'
    | '/leadi'
    | '/lead/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DarbaRindaRoute: typeof DarbaRindaRoute
  FunnelRoute: typeof FunnelRoute
  IenakosasZinasRoute: typeof IenakosasZinasRoute
  KomunikacijasRoute: typeof KomunikacijasRoute
  LeadiRoute: typeof LeadiRoute
  LeadLeadIdRoute: typeof LeadLeadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leadi': {
      id: '/leadi'
      path: '/leadi'
      fullPath: '/leadi'
      preLoaderRoute: typeof LeadiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunikacijas': {
      id: '/komunikacijas'
      path: '/komunikacijas'
      fullPath: '/komunikacijas'
      preLoaderRoute: typeof KomunikacijasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ienakosas-zinas': {
      id: '/ienakosas-zinas'
      path: '/ienakosas-zinas'
      fullPath: '/ienakosas-zinas'
      preLoaderRoute: typeof IenakosasZinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darba-rinda': {
      id: '/darba-rinda'
      path: '/darba-rinda'
      fullPath: '/darba-rinda'
      preLoaderRoute: typeof DarbaRindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead/$leadId': {
      id: '/lead/$leadId'
      path: '/lead/$leadId'
      fullPath: '/lead/$leadId'
      preLoaderRoute: typeof LeadLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DarbaRindaRoute: DarbaRindaRoute,
  FunnelRoute: FunnelRoute,
  IenakosasZinasRoute: IenakosasZinasRoute,
  KomunikacijasRoute: KomunikacijasRoute,
  LeadiRoute: LeadiRoute,
  LeadLeadIdRoute: LeadLeadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
