INSERT INTO crm.settings (setting_group, setting_key, value_json, description, is_active) VALUES
('task','task.types',
 '{"values":["call","sms","whatsapp","email","zoom","meeting","status_change","task_created","task_completed","note","other"]}'::jsonb,
 'Allowed task_type values for crm.tasks', true),
('task','task.statuses',
 '{"values":["planned","overdue","in_progress","completed","cancelled","skipped","failed"]}'::jsonb,
 'Allowed status values for crm.tasks', true),
('activity','activity.types',
 '{"values":["call","sms","whatsapp","email","zoom","meeting","status_change","task_created","task_completed","note","other"]}'::jsonb,
 'Allowed activity_type values for crm.activities', true),
('call','call.outcomes',
 '{"values":["talked","no_answer","busy","voicemail","wrong_number","callback_requested","not_interested","do_not_contact","agreed_ppv_followup"]}'::jsonb,
 'Outcome codes for completed call tasks', true),
('message','message.outcomes',
 '{"values":["sent","delivered","replied","no_reply","failed","opt_out"]}'::jsonb,
 'Outcome codes for SMS/WhatsApp/email message tasks', true),
('contact','contact.limits',
 '{"calls":4,"sms_whatsapp":2,"emails":4,"on_limit_status":"Nesasniedzams","automation_continues":true}'::jsonb,
 'Per-lead contact-attempt limits before status becomes Nesasniedzams. Automation continues.', true),
('outreach','outreach.daily_quota',
 '{"role":"Mārketings","per_ppv_user":{"UC":10,"MO":10}}'::jsonb,
 'Daily outreach quota per PPV user group, executed by role Mārketings', true),
('outreach','outreach.eligible_statuses',
 '{"values":["Jauns","Nesasniedzams"]}'::jsonb,
 'Lead statuses eligible for outreach planning', true),
('calendar','calendar.business_days',
 '{"timezone":"Europe/Riga","working_days":["Mon","Tue","Wed","Thu","Fri"],"holidays":[]}'::jsonb,
 'Business-day calendar for all schedulers', true),
('automation','automation.weekend_policy',
 '{"human_tasks_weekends_allowed":false,"manual_tasks_weekends_allowed":true,"sis_b2c_weekends_allowed":true,"sis_b2b_weekends_allowed":false}'::jsonb,
 'Weekend execution policy per actor type', true),
('ppv','ppv.auto_reschedule',
 '{"no_answer_days":2,"business_days_only":true}'::jsonb,
 'Auto-reschedule rule for PPV no_answer tasks when user does not reschedule manually', true),
('status','status.on_outcome',
 '{"not_interested":"Nekvalificējas","do_not_contact":"Nesasniedzams","opt_out":"Atlikts","agreed_ppv_followup":"Piesaistīšana"}'::jsonb,
 'Outcome → target lead status mapping', true),
('workflow','workflow.stop_rules',
 '{"Nekvalificējas":{"stops":true,"manual_resume":true},"Atlikts":{"stops":true,"manual_resume":true},"Nesasniedzams":{"stops":false,"manual_resume":true}}'::jsonb,
 'Per-status automation stop rules', true)
ON CONFLICT (setting_key) DO NOTHING;